spring:
  application:
    name: instructions-capture-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

management:
  endpoints:
    web:
      exposure:
        include: "*"

app:
  kafka:
    listener:
      enabled: true
    outbound:
      topic: instructions.outbound
      group-id: instructions-capture-service
      partitions: 1
      replication-factor: 1
    inbound:
      topic: instructions.inbound
      group-id: instructions-capture-service
      partitions: 1
      replication-factor: 1